### ISSUE TITLE
Can this be re-purposed to visualize any openapi/swagger file?

### ISSUE THREAD

**Issue by AmrEldib** [arno-di-loreto/openapi-specification-visual-documentation#1]
This looks great, I've noticed that yaml files are included to describe the openapi spec, is there a way to use a swagger yaml file and visualize its content?

**Comment by arno-di-loreto** [comment]
Thanks!
This tools was only intended to give a visual representation of the OpenAPI spec.
But I plan to work on the same thing for visualizing an OpenAPI file.
