### ISSUE TITLE
Would it be possible to add a visual indicator for required properties?

### ISSUE THREAD

**Issue by lelbil** [arno-di-loreto/openapi-specification-visual-documentation#10]
Thanks for the great visualisation, I am currently using it to learn how to write swagger files and I find it really useful. 
I do have one suggestion though, while writing my swagger file, I am iterating with the mouse over every element to know if it is required (I have no idea since I am a complete beginner), I think it would help people like me if there were any kind of visual indicator specific for required properties (say for example, the link to the property is red). I hope this could be easily achievable.

Regards

**Comment by arno-di-loreto** [comment]
That's a good idea! Now required property label should be red.

![screen shot 2018-03-04 at 15 02 14](https://user-images.githubusercontent.com/10104551/36946421-191ed11c-1fbd-11e8-99f7-5be37177ea62.png)
