### ISSUE TITLE
'further schema documentation' elements appear to be missing?

### ISSUE THREAD

**Issue by mrenvoize** [arno-di-loreto/openapi-specification-visual-documentation#8]
I can't seem to find the 'discriminator', 'readOnly', 'xml' etc keywords mentioned in your representation of the specification.. is that intentional?

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13

**Comment by arno-di-loreto** [comment]
That was a bug, I forgot to include the group fields with specific properties (e.g. the one that are not from JSON Schema). It's fixed now.
![screen shot 2017-03-19 at 23 54 19](https://cloud.githubusercontent.com/assets/10104551/24085632/93842816-0cff-11e7-9a4e-781ec19e41e8.png)

**Comment by mrenvoize** [comment]
Excellent, thank-you very much for the quick resolution, this project has quickly become my favourite way to quickly lookup schema details.

:-)
